### PR TITLE
21529

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
I has having a very hard time proving why the at-destruction-time checking of resolved names was safe and sound.  I think it's a lot better to have an *explicit* call somewhere on the screen that shows where we're doing resolving.

- - -
This change is [Reviewable](https://reviewable.io/reviews/rpoyner-tri/drake/6)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri Do you want me to rebase this before you look again?

**Comment by rpoyner-tri** [comment]
Yes, rebase, please.

**Comment by jwnimmer-tri** [comment]
Done.

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/rpoyner-tri/drake/6#-:-O-CR_2WAiEjUMo192sR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
